### ISSUE TITLE
Headlamp should contain configuration section for DefectDojo integration

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-headlamp#14]
In headlamp we have section (like gitserver, remote cluster) which contains credentials for DefectDojo integration

Acceptance Criteria:

- user can manage DD secret with Configuration section;
- inherit behaviour as for secrets for registry/sonar/nexus integration;
- in EDP env can be create only ONE secret;
- user cannot redefine name "defectdojo-ciuser-token";
- add description for each fields in DefectDojo section;
- in case if secret have ownerRef (managed by external-secret operator) lets hide button to modify object (save/remove) and add label managed-by - External secret operator (get value from secret object) like default branch

Secret Structure:

```
apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-ciuser-token
  namespace: <edp-project>
  labels:
   app.edp.epam.com/secret-type: defectdojo
data:
  token: <base64_token>
  url: <base64_url>
type: Opaque
```
