### ISSUE TITLE
Headlamp should contain configuration section for Jira integration

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-headlamp#15]
In headlamp we have section (like gitserver, remote cluster) which contains credentials for Jira integration

Acceptance Criteria:

- user can manage Jira secret with Configuration section;
- inherit behavior as for secrets for registry/sonar/nexus integration;
- in EDP env can be create only ONE secret;
- user cannot redefine name "jira-ciuser";

Secret Structure:

```
apiVersion: v1
kind: Secret
metadata:
  name: jira-user
  namespace: <edp-project>
  labels:
   app.edp.epam.com/secret-type: jira
data:
  username: <base64_token>
  password: <base64_url>
type: Opaque
```
