### ISSUE TITLE
As an EDP User, I want to use custom certificate in Headlamp deploy

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-headlamp#3]
https://epam.github.io/edp-install/operator-guide/manage-custom-certificate/?h=cert

Acceptance Criteria:

- EDP user can use own certificate to deploy Headlamp;
- add headlamp component to mkdocs article;
- use the same approach as for other components, described on mkdocs article;
- https://github.com/epam/edp-nexus-operator/commit/5fd06c9aa602c15961cc324e8863818751087e2b

**Comment by alezander86** [comment]
To use the custom certificate in Headlamp, redefine the following parameters in the [values.yaml ](https://github.com/epam/edp-headlamp/blob/master/deploy-templates/values.yaml#L117)file:

```
extraVolumes: []
  - name: custom-ca
    secret:
      defaultMode: 420
      secretName: custom-ca

extraVolumeMounts: []
  - name: custom-ca
    mountPath: /etc/ssl/certs/CA.crt
    readOnly: true
    subPath: CA.crt
```

and create a secret from your `ca.crt` file

`kubectl -n <edp-project> create secret generic custom-ca --from-file=CA.crt`
